### ISSUE TITLE
Cant place objects

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadron#26]
I place a bunch of plants or trees, press esc, and suddenly cant select or place any objects.

**Comment by vkDreamInCode** [comment]
I need a pattern, i dont have enough information based on your text

**Comment by RileyFoster** [comment]
Finished a modular building. Edited the building—deleted two objects and renamed the set. Exited the build menu to the main menu. I could not select the building I had just made or the path I had previously placed. I could access all menus and pick objects from menus, but they would not place. I could not drag the Earth in the DNA menu. I could not terraform.
