### ISSUE TITLE
Selection Box Appearing When Selecting Hatchery

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadron#30]
After placing a hatchery and left clicking on it to select, a "selection box" will appear. Left clicking appears to "reselect" the hatchery without the selection box appearing

Video Link - https://drive.google.com/open?id=1Wr0E6bJ_qKD6rSwjg6xJd4eqWzLbgsQb

Specs attached 
[specs.txt](https://github.com/mwdossantos/squadron/files/1525815/specs.txt)

**Comment by keawstudio** [comment]
It happened to me sometimes with other objects too.
