### ISSUE TITLE
Multiple clones of same visitor

### ISSUE THREAD

**Issue by keawstudio** [mwdossantos/squadron#51]
- Issue:
The visitors didn't appeared to me until I saved the park, exited the game, and loaded the park again.

Then they start to appear in groups of two or more (looks like cloning the prefab twice).
They also don't disapear when reach the entrace again.

- How to replicate:
Don't know yet, will try to create another park.

![bug_001](https://user-images.githubusercontent.com/16639616/33575557-2c78cae0-d924-11e7-8b64-19c357de3ec8.png)

**Comment by vkDreamInCode** [comment]
Do you mean the same model is used more then 1 time or?

**Comment by keawstudio** [comment]
Some of them looks like siamese twins. I the video I'll upload later it can be seen better.
