### ISSUE TITLE
Suggestion: Improve the 'you failed to get a dino or skin' screen

### ISSUE THREAD

**Issue by ElysePanici** [mwdossantos/squadron#52]
It should be completely changed for a few reasons:

- Not everyone enjoys/understands memes in games. Also, it will date your game if you include a meme.
- Its a bit obnoxious and unprofessional
- Its annoying because it occurs too often. What is the fail rate %?
- It is annoying to click the back arrow every single time you fail. Maybe you can just click out with RMB or LMB instead.

I recommend just a generic 'You failed to obtain Dinosaur DNA' or "Search for Dinosaur DNA failed' or 'You were scammed out of your money and obtained nothing', without the party streamers, the picture with the hand, etc.

**Comment by ForeverLona** [comment]
100% this. I actually found it embarrassing with my partner being in the same room, I was worried he would make a comment on it. I love memes as much as the next person and I am assuming that this will change for later releases, but it was the most off putting part of the game, bar none.

**Comment by mwdossantos** [comment]
This is actually a inside joke within the team and was put in for midnight fun's and giggles. We already have our final one in the making, which is a 3D rendered crate falling from the sky, with either a dinosaur or no dinosaur :)
