### ISSUE TITLE
The JPOG issue (suggestion)

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadron#55]
Same issue JPOG had where you cant put 2 parallel fences symmetrical on each side of one path. I understand why it does that but I still suggest a fix. 

![image](https://user-images.githubusercontent.com/34224008/33580596-6d7425d2-d913-11e7-9bbc-1477f2d20958.png)

**Comment by mwdossantos** [comment]
This is due to our grid system. We will look into this
