### ISSUE TITLE
Game Breaking Bug

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadron#6]
Placed a rock and started adjusting it, and then I suddenly couldn't adjust or select it. I then couldn't place, select or adjust any objects at all. 

I could no longer zoom out unless I pressed 'T' to go into the other camera mode. 

When I pressed 'T' it would shoot the camera out and back in, as seen in the recording.

Recording: https://drive.google.com/open?id=1-MG3iUcLr7OM3g7v7WbDhYJijs7DB9s7

**Comment by vkDreamInCode** [comment]
Can you try to use something that records in the background and then record what happends before this bugg occures? I cant really find the problem with just the result given
